### ISSUE TITLE
code review  01/07/2020

### ISSUE THREAD

**Issue by rahalrazika** [somoye123/Directory-of-programming-languages#1]
-The 1st  reviewer  said that he likes the job he suggested to add more coordinated colors especially in the navbar
-2nd reviewer claimed that it was such a good thing that he  used bootstrap and he also said that he should have removed the js code
-The 3rd reviewer added that everything was good except for the icons he said they should be changed And he also asked him to be more clear concerning explaining 
-4th reviewer said the job was done perfectly
 -5th reviewer couldn't give his review because he was ill hopefully he gets better as soon as possible

**Comment by somoye123** [comment]
All comments as been addressed and implemented as of now.
